//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 10:23:08 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ath2o.com/xml/vehicle", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ath2o.xml.vehicle;
