//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.06 at 05:46:55 PM EET 
//


package com.ath2o.xml.vehicle;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for searchCriteriaEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="searchCriteriaEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BRAND"/>
 *     &lt;enumeration value="MODEL"/>
 *     &lt;enumeration value="CLASS"/>
 *     &lt;enumeration value="ALL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "searchCriteriaEnum")
@XmlEnum
public enum SearchCriteriaEnum {

    BRAND,
    MODEL,
    CLASS,
    ALL;

    public String value() {
        return name();
    }

    public static SearchCriteriaEnum fromValue(String v) {
        return valueOf(v);
    }

}
